In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [2]:
df = pd.read_csv("Electric_Vehicle_Charging_Stations_in_New_York.csv")

In [5]:
df.info

<bound method DataFrame.info of      Fuel Type Code                                      Station Name  \
0              ELEC                                         JATC LU41
1              ELEC                                    GE WattStation
2              ELEC                                   STATION 1 @ VIL
3              ELEC                                    CITY OF ITHACA
4              ELEC                                      LANDING PARK
...             ...                                               ...
1672           ELEC         MPG 10 E 102nd Street - Tesla Destination
1673           ELEC                                     Lebrun Nissan
1674           ELEC  GGMC Parking Carnegie Garage - Tesla Destination
1675           ELEC                                   HUDSON PRESERVE
1676           ELEC   iPark 455 Central Park West - Tesla Destination

          Street Address        Intersection Directions          City State  \
0     3546 California Rd                      JATC LU41  Orchard Park    NY
1            214  3rd St                            NaN      Brooklyn    NY
2           70 E Main St  VICTOR; In lot next to church        Victor    NY
3          118 Dryden Rd              DRYDEN; 2nd floor        Ithaca    NY
4             70 Main St                    COEYMANS; -      Coeymans    NY
...                  ...                            ...           ...   ...
1672       10 E 102nd St                            NaN      New York    NY
1673       396 Grant Ave                            NaN        Auburn    NY
1674        40 E 94th St                            NaN      New York    NY
1675         8 Beryl Way                     BLDG 11 #9    Watervliet    NY
1676      27  W 105th St                            NaN      New York    NY

        ZIP  Plus4               Station Phone Status Code  ...   Latitude  \
0     14127    NaN                888-758-4389           E  ...  42.787197
1     11215    NaN                855-443-3873           E  ...  40.675331
2     14564    NaN                888-758-4389           E  ...  42.981755
3     14850    NaN                888-758-4389           E  ...  42.442142
4     12045    NaN                888-758-4389           E  ...  42.472557
...     ...    ...                         ...         ...  ...        ...
1672  10029    NaN  212-249-1947  877-798-3752           E  ...  40.791232
1673  13021    NaN                315-253-7700           E  ...  42.966894
1674  10128    NaN  212-369-9304  877-798-3752           E  ...  40.785524
1675  12189    NaN                888-758-4389           E  ...  42.731430
1676  10025    NaN  212-666-7246  877-798-3752           E  ...  40.797875

      Longitude Date Last Confirmed      ID           Updated At  \
0    -78.787821          05/27/2020   62127  2020-05-27 09:20:32
1    -73.988563          05/15/2020   73056  2020-05-15 10:00:11
2    -77.408360          05/27/2020   88701  2020-05-27 09:20:32
3    -76.486112          05/27/2020   92327  2020-05-27 09:20:32
4    -73.790396          05/27/2020   99993  2020-05-27 09:20:32
...         ...                 ...     ...                  ...
1672 -73.952370          09/30/2019  114983  2020-03-02 20:14:21
1673 -76.535879          09/09/2019   44321  2020-05-27 16:51:00
1674 -73.954960          09/30/2019  115117  2020-03-02 20:14:21
1675 -73.724330          05/27/2020  143229  2020-05-27 09:20:32
1676 -73.961228          09/30/2019  115075  2020-03-02 20:14:21

      Owner Type Code  Federal Agency ID  Federal Agency Name   Open Date  \
0                 NaN                NaN                  NaN         NaN
1                 NaN                NaN                  NaN         NaN
2                 NaN                NaN                  NaN         NaN
3                 NaN                NaN                  NaN         NaN
4                 NaN                NaN                  NaN         NaN
...               ...                ...                  ...         ...
1672                P                NaN                  NaN  09/01/2017
1673                P                NaN                  NaN  11/30/2011
1674                P                NaN                  NaN  11/01/2018
1675              NaN                NaN                  NaN         NaN
1676                P                NaN                  NaN  08/15/2016

     EV Connector Types
0                 J1772
1                 J1772
2                 J1772
3                 J1772
4                 J1772
...                 ...
1672        J1772 TESLA
1673              J1772
1674        J1772 TESLA
1675              J1772
1676        J1772 TESLA

[1677 rows x 31 columns]>

In [6]:
#get the dataframe columns
cols = df.columns 

#print the columns
print(cols)

Index(['Fuel Type Code', 'Station Name', 'Street Address',
       'Intersection Directions', 'City', 'State', 'ZIP', 'Plus4',
       'Station Phone', 'Status Code', 'Expected Date',
       'Groups With Access Code', 'Access Days Time', 'Cards Accepted',
       'EV Level1 EVSE Num', 'EV Level2 EVSE Num', 'EV DC Fast Count',
       'EV Other Info', 'EV Network', 'EV Network Web', 'Geocode Status',
       'Latitude', 'Longitude', 'Date Last Confirmed', 'ID', 'Updated At',
       'Owner Type Code', 'Federal Agency ID', 'Federal Agency Name',
       'Open Date', 'EV Connector Types'],
      dtype='object')

In [7]:
df.head(10)

,Fuel Type Code,Station Name,Street Address,Intersection Directions,City,State,ZIP,Plus4,Station Phone,Status Code,...,Latitude,Longitude,Date Last Confirmed,ID,Updated At,Owner Type Code,Federal Agency ID,Federal Agency Name,Open Date,EV Connector Types
0,ELEC,JATC LU41,3546 California Rd,JATC LU41,Orchard Park,NY,14127,NaN,888-758-4389,E,...,42.787197,-78.787821,05/27/2020,62127,2020-05-27 09:20:32,NaN,NaN,NaN,NaN,J1772
1,ELEC,GE WattStation,214 3rd St,NaN,Brooklyn,NY,11215,NaN,855-443-3873,E,...,40.675331,-73.988563,05/15/2020,73056,2020-05-15 10:00:11,NaN,NaN,NaN,NaN,J1772
2,ELEC,STATION 1 @ VIL,70 E Main St,VICTOR; In lot next to church,Victor,NY,14564,NaN,888-758-4389,E,...,42.981755,-77.408360,05/27/2020,88701,2020-05-27 09:20:32,NaN,NaN,NaN,NaN,J1772
3,ELEC,CITY OF ITHACA,118 Dryden Rd,DRYDEN; 2nd floor,Ithaca,NY,14850,NaN,888-758-4389,E,...,42.442142,-76.486112,05/27/2020,92327,2020-05-27 09:20:32,NaN,NaN,NaN,NaN,J1772
4,ELEC,LANDING PARK,70 Main St,COEYMANS; -,Coeymans,NY,12045,NaN,888-758-4389,E,...,42.472557,-73.790396,05/27/2020,99993,2020-05-27 09:20:32,NaN,NaN,NaN,NaN,J1772
5,ELEC,GLOVERS PARKING,85 Mill Rd,STATION 1STATION 2,Westhampton Beach,NY,11978,NaN,888-758-4389,E,...,40.811928,-72.643211,05/27/2020,103139,2020-05-27 09:20:32,NaN,NaN,NaN,NaN,J1772
6,ELEC,TOWNOFLEWISTON1,1375 Ridge Rd,LEWITSON 1,Lewiston,NY,14092,NaN,888-758-4389,E,...,43.179582,-78.984100,05/27/2020,104778,2020-05-27 09:20:32,NaN,NaN,NaN,NaN,J1772
7,ELEC,Best Western Saranac Lake - Tesla Destination,487 Lake Flower Ave,NaN,Saranac Lake,NY,12983,NaN,518-891-1970 877-798-3752,E,...,44.314712,-74.119133,09/30/2019,150637,2020-03-02 20:14:21,P,NaN,NaN,09/30/2019,TESLA
8,ELEC,DEFREETSVILLE 1,649 Bloomingrove Dr,DEFREESTVILLE; Back corner of park and ride lot,Rensselaer,NY,12144,NaN,888-758-4389,E,...,42.652680,-73.696239,05/27/2020,99372,2020-05-27 09:20:32,NaN,NaN,NaN,NaN,J1772
9,ELEC,iPark NYC 88th Street Garage - Tesla Destination,101 W 88th St,NaN,New York,NY,10024,NaN,212-874-8442 877-798-3752,E,...,40.787976,-73.971145,09/30/2019,114993,2020-03-02 20:14:21,P,NaN,NaN,05/01/2016,J1772 TESLA

In [9]:
data = df.drop(['Plus4','Station Phone', 'Status Code', 'Expected Date',
       'Groups With Access Code', 'Access Days Time', 'Cards Accepted',
       'EV Level1 EVSE Num', 'EV Level2 EVSE Num', 'EV DC Fast Count',
       'EV Other Info', 'EV Network', 'EV Network Web', 'Geocode Status',
       'Date Last Confirmed', 'ID', 'Updated At',
       'Owner Type Code', 'Federal Agency ID', 'Federal Agency Name',
       'Open Date', 'EV Connector Types'],axis=1)

In [10]:
data.head()

,Fuel Type Code,Station Name,Street Address,Intersection Directions,City,State,ZIP,Latitude,Longitude
0,ELEC,JATC LU41,3546 California Rd,JATC LU41,Orchard Park,NY,14127,42.787197,-78.787821
1,ELEC,GE WattStation,214 3rd St,NaN,Brooklyn,NY,11215,40.675331,-73.988563
2,ELEC,STATION 1 @ VIL,70 E Main St,VICTOR; In lot next to church,Victor,NY,14564,42.981755,-77.408360
3,ELEC,CITY OF ITHACA,118 Dryden Rd,DRYDEN; 2nd floor,Ithaca,NY,14850,42.442142,-76.486112
4,ELEC,LANDING PARK,70 Main St,COEYMANS; -,Coeymans,NY,12045,42.472557,-73.790396

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1677 entries, 0 to 1676
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Fuel Type Code           1677 non-null   object
 1   Station Name             1677 non-null   object
 2   Street Address           1677 non-null   object
 3   Intersection Directions  773 non-null    object
 4   City                     1677 non-null   object
 5   State                    1677 non-null   object
 6   ZIP                      1677 non-null   int64
 7   Latitude                 1677 non-null   float64
 8   Longitude                1677 non-null   float64
dtypes: float64(2), int64(1), object(6)
memory usage: 118.0+ KB

In [12]:
data[['ZIP']].describe()

                ZIP
count   1677.000000
mean   12064.155039
std     1506.032119
min    10001.000000
25%    10595.000000
50%    12110.000000
75%    13021.000000
max    14901.000000